spring:
     thymeleaf:
          mode: HTML5
          encoding: UTF-8
          # 开发禁用缓存
          cache: false
          servlet:
               content-type: text/html
     datasource:
          url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123
          # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
          # driver-class-name: com.mysql.jdbc.Driver
          hikari:
               connection-timeout: 60000
mybatis:
     mapperLocations: classpath:mapper/*.xml
     typeAliasesPackage: com.example.demo.domain
     #mybatis数据库转驼峰式名命（注意数据库命名要小写，大写转不了驼峰[未验证]）
     configuration:
          map-underscore-to-camel-case: true

# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
     level:
          root: info